### ISSUE TITLE
double in core_permission

### ISSUE THREAD

**Issue by ant2526** [KejawenLab/SemartApiSkeleton#115]
data double di field core_permission, ketika generate menggunakan generator

**Comment by ad3n** [comment]
@ant2526 bisa direproduce stepnya ga mas? sama bantuan SS atau sejenisnya biar lebih mudah

**Comment by ant2526** [comment]
Stepnya saya ngikuti di https://github.com/KejawenLab/SemartApiSkeleton
Membuat Todo, sampai selesai
Setelah itu saya buka menu hak akses dan hasilnya double
seperti gambar ini :
![double app](https://user-images.githubusercontent.com/2320784/150074712-6b364459-07d6-4c02-aee5-6f62c52b208e.jpeg)
![double db](https://user-images.githubusercontent.com/2320784/150074697-e72dd81f-2582-415e-b99e-fa324c05bcfb.jpeg)
sudah tak cari di dalam folder command dan sampai sekarang belum ketemu mas...

**Comment by ad3n** [comment]
@ant2526  fixed #a52bfe0d0b144ed5bfcd7ad6dd5d7857d5002276

**Comment by ant2526** [comment]
Terimakasih
