### ISSUE TITLE
API /api/me PUT

### ISSUE THREAD

**Issue by ant2526** [KejawenLab/SemartApiSkeleton#117]
di bagian /api/me dengan method PUT, belum ada upload file seperti di admin.

**Comment by ad3n** [comment]
@ant2526 secara code sudah ada, cuma memang kelupaan untuk update annotation-nya

Akan segera update, atau Anda mau bantu PR?

**Comment by ad3n** [comment]
<img width="1360" alt="Screen Shot 2022-01-29 at 10 29 48" src="https://user-images.githubusercontent.com/7464920/151645759-dc5a590b-f3ca-41d7-93f2-6cccae472084.png">
done
