### ISSUE TITLE
KejawenLab\ApiSkeleton\Form\FormFactory tidak bisa menerima data type="file"

### ISSUE THREAD

**Issue by ant2526** [KejawenLab/SemartApiSkeleton#119]
Pada KejawenLab\ApiSkeleton\Form\FormFactory tidak bisa menerima data type="file".

Contohnya di file :

https://github.com/KejawenLab/SemartApiSkeleton/blob/main/lib/Controller/Me/Put.php

$form['file']->getData() selalu null.

**Comment by ad3n** [comment]
Fix: with commit #https://github.com/KejawenLab/SemartApiSkeleton/commit/483f1eb55e9819b255a76683897c5235ec139486
